#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 02/10/2025
set -ueox pipefail

source "./home"
source "${HUSK_HOME}/rake" "${1}" "${2}"
"$(which podman)" container stop "${WHICH_POD}" || true
"$(which podman)" container rm --force "${WHICH_POD}"
"$(which podman)" run --name "${WHICH_POD}" -v "${HUSK_HOME}":"${HUSK_HOME}":z -it "${WHICH_SOIL/.soil/}:latest" "/bin/bash"