#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 02/06/2025
set -ueox pipefail

function removeContainer() {
    podman container rm --force "${1}"
}

function removeStoppedContainers() {
    podman container rm --force $(podman container ls --filter "status=exited" --format='{{.Names}}' | grep -e "soil") || true
}

function removeAllContainers() {
    podman container rm --force $(podman container ls --format='{{.Names}}' | grep -e "soil") || true
}

function removeImage() {
    podman image rm --force "${1}"
}

function removeAllImages() {
    podman image rm --force $(podman image ls --format='{{.Repository}}' | grep -e "soil") || true
}

function removeCob() {
    find "./silo/cobs/${1}" -name "*.cob" -type f -delete
    find "./silo/cobs/${1}" -name "*.soil" -type f -delete
    rm -rf "./.cob/${1}"
}

function removeAllCobs() {
    find "./silo/cobs" -name "*.cob" -type f -delete
    find "./silo/cobs" -name "*.soil" -type f -delete
    rm -rf "./.cob"
}

function removeNursery() {
    rm -rf "./.nursery/${1}"
}

function removeAllSeeds() {
    find . -name "*.tar.bz2" -type f -delete
    find . -name "*.tar.gz" -type f -delete
    find . -name "*.zip" -type f -delete
    find . -name "*.git" -type f -delete
}

function removeFarm() {
    rm -rf "./.farm/${1}"
}

function removeAllFarms() {
    rm -rf "./.farm"
}

function removeHarvest() {
    rm -rf "./.harvest/${1}"
}

function removeAllHarvests() {
    rm -rf "./.harvest"
}

if [[ "${@}" =~ ^container' '.*$ ]]; then
    removeContainer "${2}"
elif [[ "${@}" =~ ^stopped' 'containers$ ]]; then
    removeStoppedContainers
elif [[ "${@}" =~ ^all' 'containers$ ]]; then
    removeAllContainers
elif [[ "${@}" =~ ^image' '.*$ ]]; then
    removeImage "${2}"
elif [[ "${@}" =~ ^all' 'images$ ]]; then
    removeAllImages
elif [[ "${@}" =~ ^cob' '.*$ ]]; then
    removeCob "${2}"
elif [[ "${@}" =~ ^all' 'cobs$ ]]; then
    removeAllCobs
elif [[ "${@}" =~ ^all' 'seeds$ ]]; then
    removeAllSeeds
elif [[ "${@}" =~ ^farm' '.*$ ]]; then
    removeFarm "${2}"
elif [[ "${@}" =~ ^all' 'farms$ ]]; then
    removeAllFarms
elif [[ "${@}" =~ ^all' 'soils$ ]]; then
    removeAllContainers
    removeAllImages
elif [[ "${@}" =~ ^all' 'silos$ ]]; then
    removeAllFarms
    removeAllHarvests
    removeAllCobs
elif [[ "${@}" =~ ^all$ ]]; then
    removeAllContainers
    removeAllImages
    removeAllSeeds
    removeAllCobs
    removeAllFarms
    removeAllHarvests
fi
