#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 02/06/2025
set -ueox pipefail

function removePod() {
    "$(which podman)" container rm --force "${1}"
}

function removeStoppedPods() {
    "$(which podman)" container rm --force $("$(which podman)" container ls --filter "status=exited" --format='{{.Names}}' | grep -e "soil") || true
}

function removeAllPods() {
    removeStoppedPods
    "$(which podman)" container rm --force $("$(which podman)" container ls --format='{{.Names}}' | grep -e "soil") || true
}

function removeLog() {
    rm -rf "./.log/${1}"
}

function removeAllLogs() {
    rm -rf "./.log"
}

function removeImage() {
    "$(which podman)" image rm --force "${1}"
}

function removeAllImages() {
    "$(which podman)" image rm --force $("$(which podman)" image ls --format='{{.Repository}}' | grep -e "soil") || true
}

function removeCob() {
    find "./silo/cobs/" -name "*${1}.cob" -type f -delete
    find "./silo/cobs" -name "*${1}.soil" -type f -delete
    rm -rf "./.cob/${1}"
}

function removeAllCobs() {
    find "./silo/cobs" -name "*.cob" -type f -delete
    find "./silo/cobs" -name "*.soil" -type f -delete
    rm -rf "./.cob"
}

function removeAllSeeds() {
    find "./silo" -name "*.tar.bz2" -type f -delete
    find "./silo" -name "*.tar.gz" -type f -delete
    find "./silo" -name "*.zip" -type f -delete
    find "./silo" -name "*.git" -type f -delete
}

function removeFarm() {
    rm -rf "./.farm/${1}"
}

function removeAllFarms() {
    rm -rf "./.farm"
}

function removeHarvest() {
    rm -rf "./.harvest/${1}"
}

function removeAllHarvests() {
    rm -rf "./.harvest"
}

if [[ "${@}" =~ ^pod' '.*$ ]]; then
    removePod "${2}"
elif [[ "${@}" =~ ^stopped' 'pods$ ]]; then
    removeStoppedPods
elif [[ "${@}" =~ ^all' 'pods$ ]]; then
    removeAllPods
elif [[ "${@}" =~ ^log' '.*$ ]]; then
    removeLog "${2}"
elif [[ "${@}" =~ ^all' 'logs$ ]]; then
    removeAllLogs
elif [[ "${@}" =~ ^image' '.*$ ]]; then
    removeImage "${2}"
elif [[ "${@}" =~ ^all' 'images$ ]]; then
    removeAllImages
elif [[ "${@}" =~ ^cob' '.*$ ]]; then
    removeCob "${2}"
elif [[ "${@}" =~ ^all' 'cobs$ ]]; then
    removeAllCobs
elif [[ "${@}" =~ ^all' 'seeds$ ]]; then
    removeAllSeeds
elif [[ "${@}" =~ ^farm' '.*$ ]]; then
    removeFarm "${2}"
elif [[ "${@}" =~ ^all' 'farms$ ]]; then
    removeAllFarms
elif [[ "${@}" =~ ^all' 'soils$ ]]; then
    removeAllPods
    removeAllImages
elif [[ "${@}" =~ ^all' 'silos$ ]]; then
    removeAllFarms
    removeAllHarvests
    removeAllCobs
elif [[ "${@}" =~ ^all$ ]]; then
    removeAllPods
    removeAllImages
    removeAllSeeds
    removeAllCobs
    removeAllFarms
    removeAllHarvests
    removeAllLogs
    rm -rf "./.husk"
fi
