#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 02/09/2025
set -ueox pipefail
source ./rake "${1}" "${2}"
./gather "${WHICH_SILO}" "${WHICH_SOIL}"
./spin "${WHICH_SILO}" "${WHICH_SOIL}"
./nursery "${WHICH_SILO}" "${WHICH_SOIL}"
