#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 02/19/2025
set -ueox pipefail
source "./.husk"
WHICH_SOIL="${1}"
WHICH_SILO="empty.cob"
WHICH_POD="${WHICH_SILO}.${WHICH_SOIL}"
WHICH_FARMER="${2}"
[[ "${WHICH_FARMER}" =~ .*.farmer$ ]] && WHICH_FARMER="${2/.farmer/}" || WHICH_FARMER="root"
./clear image "${WHICH_POD}"
"$(which podman)" build --no-cache -t "${WHICH_POD}" -f "./silo/soils/${WHICH_SOIL}" . \
    --build-arg WHICH_FARMER="${WHICH_FARMER}"
./clear pod "${WHICH_POD}"
"$(which podman)" run --name "${WHICH_POD}" -v "${HUSK_HOME}":"${HUSK_HOME}":z \
    --workdir="${HUSK_HOME}" --user "${WHICH_FARMER}" -it "${WHICH_POD}" "/bin/bash"
