#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 01/28/2025
set -ueox pipefail
source ./rake "${1}"
rm -rf "${HUSK_HOME}/wip"
podman container stop "${WHICH_POD}" && true
podman container rm --force "${WHICH_POD}"
if [[ $WHICH_POD =~ ^husk.wip ]]; then
    podman run --name "${WHICH_POD}" -e COB_PATH="${COB_PATH}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -it "soil.${WHICH_POD}"  "/bin/bash"
else
    podman run -d --name "${WHICH_POD}" -e COB_PATH="${COB_PATH}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "soil.${WHICH_POD}" "${SOIL_HOME}/unshell" "${COB_PATH}"
fi
