#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 01/28/2025
set -ueox pipefail
source ./rake "${1}"

function clear() {
    podman container stop "${1}" && true
    podman container rm --force "${1}"
}

if [[ $WHICH =~ .*cob$ ]]; then
    clear "${WHICH}"
    podman run -d --name "${WHICH}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH}" "${SOIL_HOME}/unshell" "${1}"
elif [[ $WHICH =~ .*farm$ ]]; then
    clear "${WHICH}"
    podman run -d --name "${WHICH}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH}" "${SOIL_HOME}/plant" "${1}"
elif [[ $WHICH =~ .*empty$ ]]; then
    clear "${WHICH}"
    podman run -d --name "${WHICH}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH}" "/bin/bash"
else
    echo "cannot nursery unsupported soil" && exit 1
fi
