#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 01/28/2025
set -ueox pipefail

source ./rake "${1}" "${2}"

function clear() {
    podman container stop "${WHICH_POD}" || true
    podman container rm --force "${WHICH_POD}"
}

if [[ "${WHICH_SILO}" =~ .*cob$ ]]; then
    clear "${WHICH_POD}"
    podman run -d --name "${WHICH_POD}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH_POD}" "$(which bash)" "${SOIL_HOME}/unshell" "${WHICH_SILO}" "${WHICH_SOIL}"
elif [[ "${WHICH_SILO}" =~ .*farm$ ]]; then
    $(which bash) -c "${RAKE_PATH}"
elif [[ "${WHICH_SILO}" =~ .*harvest$ ]]; then
    clear "${WHICH_POD}"
    podman run -d --name "${WHICH_POD}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH_POD}" "$(which bash)" "${SOIL_HOME}/${RAKE_PATH}" "${WHICH_SILO}" "${WHICH_SOIL}"
else
    echo "cannot nursery unsupported silo, can be cob or farm" && exit 1
fi
