#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 01/28/2025
set -ueox pipefail
source ./rake "${1}" "${2}"

function clear() {
    podman container stop "${WHICH_POD}" || true
    podman container rm --force "${WHICH_POD}"
}

if [[ "${WHICH_SILO}" =~ .*cob$ ]]; then
    clear "${WHICH_POD}"
    podman run -d --name "${WHICH_POD}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH_POD}" "${SOIL_HOME}/unshell" "${WHICH_SILO}" "${WHICH_SOIL}"
elif [[ "${WHICH_SILO}" =~ .*farm$ ]]; then
    clear "${WHICH_POD}"
    podman run -d --name "${WHICH_POD}" -v "${HUSK_HOME}":"${SOIL_HOME}":z -t "${WHICH_POD}" "${SOIL_HOME}/farm" "${WHICH_SILO}" "${WHICH_SOIL}"
else
    echo "cannot nursery unsupported silo, can be cob or farm" && exit 1
fi
