#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 01/28/2025
set -ueox pipefail
source "./.husk"
source "${HUSK_HOME}/rake" "${1}" "${2}"
WHICH_FARMER="${3}"
[[ "${WHICH_FARMER}" =~ .*.farmer$ ]] && WHICH_FARMER="${3/.farmer/}" || WHICH_FARMER="root"
"$(which podman)" container stop "${WHICH_POD}" || true
"$(which podman)" commit "${WHICH_POD}" "${WHICH_POD}.revived"
"$(which podman)" container rm --force "${WHICH_POD}.revived"
"$(which podman)" run -d --name "${WHICH_POD}.revived" -v "${HUSK_HOME}":"${HUSK_HOME}":z \
     --workdir="${HUSK_HOME}" --userns=keep-id --user "${WHICH_FARMER}" -t "${WHICH_POD}.revived" "$(which bash)"
