#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 02/8/2025
set -ueox pipefail
SEED=$1
URL=$2
VERSION=$3

HUSK_HOME="${PWD}"
EPHEMERAL="${HUSK_HOME}/.seed"
rm -rf "${EPHEMERAL}"
mkdir -p "${EPHEMERAL}"
cd "${EPHEMERAL}"

NEW_SEED="${HUSK_HOME}/silo/seeds/${SEED}"
mkdir -p "${NEW_SEED}"

NEW_SEED_VERSION="${NEW_SEED}/${VERSION}.seed"
rm -rf "${NEW_SEED_VERSION}"
touch "${NEW_SEED_VERSION}"

SOURCE=""
CHECKSUM=""
if [[ $URL =~ .*.git$ ]]; then
    git clone "${URL}" --depth=1
    SOURCE=$(echo $(find ./ -maxdepth 1 -type d -printf "%f~" | cut -d "~" -f 2))
    cd "${SOURCE}"
    COMMIT=$(git rev-parse HEAD)
    printf "DEPENDENCIES=()\nURL=\"${URL}\"\nCOMMIT=\"${COMMIT}\"\nSOURCE=\"${SOURCE}\"" >> "${NEW_SEED_VERSION}"
else
    curl -sLO "${URL}"
    ARCHIVE=$(basename "${URL}")
    case $(echo "${ARCHIVE##*.}") in
        "bz2")
            tar -xf "${ARCHIVE}";;
        "gz")
            tar -xzf "${ARCHIVE}";;
        "zip")
            unzip "${ARCHIVE}";;
        "git")
            tar -xzf "${ARCHIVE}";;
        *)
            exit 1 ;;
    esac
    CHECKSUM=$(sha256sum "${ARCHIVE}" | cut -d " " -f 1)
    SOURCE=$(echo $(find ./ -maxdepth 1 -type d -printf "%f~" | cut -d "~" -f 2))
    printf "DEPENDENCIES=()\nURL=\"${URL}\"\nCHECKSUM=\"${CHECKSUM}\"\nSOURCE=\"${SOURCE}\"\n" >> "${NEW_SEED_VERSION}"
fi
rm -rf "${EPHEMERAL}"


