#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 12/21/2024
set -ueox pipefail
URL=$1 && CHECKSUM=$2 && TEMP=$3 && PAYLOAD=$4
if [[ -f "/.husk/.bob" ]] ; then source /.husk/.bob ; fi

function seedFromArchive {
  wget --directory-prefix "${TEMP}" "https://${URL}"
  TARBALL=$(echo "${URL##*/}") && echo "${CHECKSUM} ${TEMP}${TARBALL}" | sha256sum --check --status
  case $(echo "${TARBALL##*.}") in
    "bz2")
      tar -xf "${TEMP}${TARBALL}" -C "${TEMP}" ;;
    "gz")
      tar -xzf "${TEMP}${TARBALL}" -C "${TEMP}" ;;
    *)
      exit 1 ;;
  esac
}

function seedFromGit {
  if [[ -f "/.husk/.bob" ]] ; then git clone "https://${GITHUB_USER}:${GITHUB_TOKEN}@${URL}" "${TEMP}${PAYLOAD}"; else git clone "https://${URL}" "${TEMP}${PAYLOAD}"; fi
}


if [[ "$URL" =~ \.git$ ]]; then
  seedFromGit
else
  seedFromArchive
fi

