#!/bin/sh
# Author: Shree Raj Shrestha
# Date: 01/20/2025
set -ueox pipefail
source /soil/rake "${1}"
mkdir -p "${EPHEMERAL}"

source "${SOIL_HOME}/silo/seeds/$(echo "${2}" | cut -d "_" -f 1)/$(echo "${2}" | cut -d "_" -f 2).seed"
ARCHIVE=$(echo "${URL##*/}")
cd "${SOIL_HOME}/silo/seeds/$(echo "${2}" | cut -d "_" -f 1)/"
case $(echo "${ARCHIVE##*.}") in
    "bz2")
        tar -xvf "${ARCHIVE}" -C "${EPHEMERAL}";;
    "gz")
        tar -xvzf "${ARCHIVE}" -C "${EPHEMERAL}";;
    "zip")
        unzip "${ARCHIVE}" -d "${EPHEMERAL}";;
    "git")
        tar -xvzf "${ARCHIVE}" -C "${EPHEMERAL}";;
    *)
        exit 1 ;;
esac

WHICH_SEED="$(echo "${2}" | cut -d "_" -f 1)"
source "${SOIL_HOME}/silo/seeds/$(echo "${2}" | cut -d "_" -f 1)/$(echo "${2}" | cut -d "_" -f 3).recipe"
cd "${EPHEMERAL}/${SOURCE}"
for STEP in "${STEPS[@]}"; do eval "${STEP}"; done
rm -rf "${EPHEMERAL}"
