#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 01/20/2025
set -ueox pipefail
source "${HUSK_HOME}/home"
source "${HUSK_HOME}/rake" "${1}" "${2}"
THIS_KERNEL="${3}"
EPHEMERAL="${HOME}/.ephemeral/${RANDOM}"
mkdir -p "${EPHEMERAL}"

THIS_SEED="$(echo "${THIS_KERNEL}" | cut -d "_" -f 1)"
SEED_FILE="${HUSK_HOME}/silo/seeds/${THIS_SEED}/$(echo "${THIS_KERNEL}" | cut -d "_" -f 2).seed"
RECIPE_FILE="${HUSK_HOME}/silo/seeds/${THIS_SEED}/$(echo "${THIS_KERNEL}" | cut -d "_" -f 3).recipe"

source "${SEED_FILE}"
ARCHIVE=$(echo "${URL##*/}")
cd "$(dirname "${SEED_FILE}")"
case $(echo "${ARCHIVE##*.}") in
    "bz2")
        tar -xvf "${ARCHIVE}" -C "${EPHEMERAL}";;
    "gz")
        tar -xvzf "${ARCHIVE}" -C "${EPHEMERAL}";;
    "zip")
        unzip "${ARCHIVE}" -d "${EPHEMERAL}";;
    "git")
        tar -xvzf "${ARCHIVE}" -C "${EPHEMERAL}";;
    *)
        exit 1 ;;
esac

"$(which bash)" "${HUSK_HOME}/unshell" "${WHICH_SILO}" "${WHICH_SOIL}" "${SEED_FILE}" "${RECIPE_FILE}" "${EPHEMERAL}/${SOURCE}"
rm -rf "${EPHEMERAL}"
