#!/bin/bash
# Author: Shree Raj Shrestha
# Date: 01/30/2025
set -ueox pipefail

source "${HUSK_HOME}/home"
source "${HUSK_HOME}/rake" "${1}" "${2}"
source "${HUSK_HOME}/${RAKE_PATH}"
for SEED in "${COB[@]}"; do
    if [ ! -d "${HUSK_HOME}/${COB_HOME}/${WHICH_POD}/$(echo "${SEED}" | cut -d "_" -f 1)" ]; then
        "$(which bash)" "${HUSK_HOME}/sprout" "${SEED}" "${WHICH_POD}"
    fi
done