COB=(zlib_latest_serial hdf5_latest_serial openmpi_latest_serial fftw_latest_serial gklib_latest_serial metis_latest_serial gsl_latest_serial numa_latest_serial jemalloc_latest_serial cfitsio_latest_default healpix_latest_default swiftsim_latest_serial)
REQUIREMENTS="sh tar unzip gcc g++ autoconf automake @development-tools libtool cmake diff"
